### PR TITLE
Fix issue 31 & 32

### PR DESCRIPTION
**Pull request by erikwaskiewicz**
- Optimise queries for classifications and variants page to speed up database
- use `select_related` and `prefetch_related` Django functions to do this - gets all data in single query, rather than repeatedly querying the database

### CODE REVIEW

**Comment by erikwaskiewicz** [comment]
Commits above fix issue #31 for classifications and variants page. Still need to optimise other pages

**Comment by erikwaskiewicz** [comment]
Commits from be792b1  onwards fix issue #32

**Comment by josephhalstead** [comment]
All looks good. Nice changes - added code to blank out genuine form button once clicked as an extra feature.

**Comment by erikwaskiewicz** [comment]
Thanks!
I tested the code to blank out the button - all works as expected

**Pull request merged**
