### PR TITLE
CNV Database

### PR DESCRIPTION
**Pull request by SophieS9**
Merging CNV database to development branch. 

- Manual tests carried out with real data. 
- Unit test scripts written with fake data that are run using: `python manage.py test -v 2`

### CODE REVIEW

**Comment by josephhalstead** [comment]
Just adding notes for review:

1) Failure when changing Gain to Loss or Loss to Gain. First Check > Switch Gain to Loss > Questions are Gain

**Comment by josephhalstead** [comment]
Disable ability to switch classification from loss to gain or otherwise in second check - will be too complicated.

**Comment by josephhalstead** [comment]
Can we move genome build onto CNVVariant object. Need to make sure a specific variant is attached to a known genome build.

For example 1:100-200 (37) and 1:100-200 (38) are different variants, but no way to know this at the moment. I think this will fix bug where if same variant is uploaded in different builds it crashes.

```
MultipleObjectsReturned at /cnv_home/
get() returned more than one CNV -- it returned 2!
```

**Comment by SophieS9** [comment]
1. Failure when changing Gain to Loss or Loss to Gain. First Check > Switch Gain to Loss > Questions are Gain - fixed in commit  https://github.com/AWGL/variant_classification_DB/pull/45/commits/1202a74f630987821996bf635f99855a52f22537 
2. Disable ability to switch classification from loss to gain or otherwise in second check - will be too complicated. - fixed in commits https://github.com/AWGL/variant_classification_DB/pull/45/commits/64f1785512b2e8e36dc2ecce6064458d2789a190 and https://github.com/AWGL/variant_classification_DB/pull/45/commits/49b3ca2b16948847d78576554ffc2d6fe1026001
3. Can we move genome build onto CNVVariant object. Need to make sure a specific variant is attached to a known genome build. - fixed in commit https://github.com/AWGL/variant_classification_DB/pull/45/commits/4bc2c9582b11647685e83ce041b8d7665271d776
4.  Error in https://github.com/AWGL/variant_classification_DB/pull/45#issuecomment-900382798 was actually due to same sample being reanalysed from multiple worksheets. Updated code to allow this. Fixed in commit https://github.com/AWGL/variant_classification_DB/pull/45/commits/c7626d8fc39f15642f29b3c48042b8af7e41992b

**Comment by josephhalstead** [comment]
reviewed - all looks good.

**Pull request merged**
